email:
  subject: "CaliforniaFIRST Completion Certificate"
  blurb: "Thank you for financing your home energy improvements through the CaliforniaFIRST Program. This email provides the Completion Certificate for your signature. You must sign the necessary documents within 5 days of receiving this email. You can continue to use this link to return to DocuSign and download your materials. If you have any questions, please call us at (844) 589-7953."
