version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g serverless@3.39.0
      - npm install
  build:
    commands:
      - serverless deploy --stage dev

cache:
  paths:
    - node_modules
