// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Tiro-Js APIs",
    "version": "1"
  },
  "paths": {
    "/docusign_connect": {
      "post": {
        "summary": "docusign_connect",
        "description": "",
        "operationId": "docusign_connect.post.docusign_connect",
        "consumes": [
          "application/xml"
        ],
        "produces": [
          "application/xml"
        ],
        "security": [
          {
            "Api-Token": [],
            "x-api-key": [],
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/DocuSignEnvelopeInformation"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/docu_sign/envelopes/{envelope_uuid}": {
      "get": {
        "summary": "getEnvelope",
        "description": "",
        "operationId": "getEnvelope.get.docu_sign/envelopes/{envelope_uuid}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Api-Token": [],
            "x-api-key": [],
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "name": "envelope_uuid",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/signature_requests/{signature_id}/recipients/{recipient_id}/signing_url": {
      "get": {
        "summary": "signingUrl",
        "description": "",
        "operationId": "signingUrl.get.signature_requests/{signature_id}/recipients/{recipient_id}/signing_url",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Api-Token": [],
            "x-api-key": [],
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "name": "signature_id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "recipient_id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/signature_requests/{signature_id}/recipients/{recipient_id}": {
      "patch": {
        "summary": "updateRecipient",
        "description": "",
        "operationId": "updateRecipient.patch.signature_requests/{signature_id}/recipients/{recipient_id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Api-Token": [],
            "x-api-key": [],
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateRecipientRequest"
            }
          },
          {
            "name": "signature_id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "recipient_id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/signature_requests/{signature_id}/recipients/{recipient_id}/resend_email": {
      "post": {
        "summary": "resendEmail",
        "description": "",
        "operationId": "resendEmail.post.signature_requests/{signature_id}/recipients/{recipient_id}/resend_email",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Api-Token": [],
            "x-api-key": [],
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "name": "signature_id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "recipient_id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "UpdateRecipientRequest": {
      "properties": {
        "signature_id": {
          "title": "UpdateRecipientRequest.signature_id",
          "type": "string"
        },
        "recipient_id": {
          "title": "UpdateRecipientRequest.recipient_id",
          "type": "string"
        },
        "email": {
          "title": "UpdateRecipientRequest.email",
          "type": "string"
        },
        "name": {
          "title": "UpdateRecipientRequest.name",
          "type": "string"
        },
        "contractor_user_identifier": {
          "title": "UpdateRecipientRequest.contractor_user_identifier",
          "type": "string"
        },
        "program_identifier": {
          "title": "UpdateRecipientRequest.program_identifier",
          "type": "string"
        },
        "override": {
          "title": "UpdateRecipientRequest.override",
          "type": "boolean"
        }
      },
      "required": [
        "signature_id",
        "recipient_id",
        "email",
        "name",
        "contractor_user_identifier",
        "program_identifier",
        "override"
      ],
      "additionalProperties": false,
      "title": "UpdateRecipientRequest",
      "type": "object"
    },
    "DocuSignEnvelopeInformation": {
      "title": "DocuSignEnvelopeInformation",
      "type": "string"
    }
  },
  "securityDefinitions": {
    "Api-Token": {
      "type": "apiKey",
      "name": "Api-Token",
      "in": "header"
    },
    "x-api-key": {
      "type": "apiKey",
      "name": "x-api-key",
      "in": "header"
    },
    "Authorization": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "basePath": "/docusign-wrapper-api",
  "host": "dev.api.renewfinancial.com",
  "schemes": [
    "https",
    "http"
  ]
};